# Generated by Django 5.1.2 on 2024-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='resource',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='resource_photos/'),
        ),
    ]
