# Generated by Django 5.1.2 on 2024-11-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_remove_resource_image_urls_resource_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='is_negotiable',
            field=models.BooleanField(default=True),
        ),
    ]
