# Generated by Django 5.1.2 on 2024-10-29 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=255)),
                ('course_or_company', models.CharField(max_length=255)),
                ('year_of_joining', models.IntegerField()),
                ('bio', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.user')),
            ],
        ),
    ]
